### ISSUE TITLE
CUDA Instead of CPU?

### ISSUE THREAD

**Issue by NiallMcCann96** [vndee/local-talking-llm#10]
Any tips for getting this up and running with CUDA instead?

**Comment by vndee** [comment]
Hey @NiallMcCann96,

Two out of three key components will automatically use CUDA if it's available:

1. **`SpeechToTextService`**: The Whisper model leverages CUDA automatically if detected. You can check this in the code here: [Whisper CUDA Check](https://github.com/openai/whisper/blob/279133e3107392276dc509148da1f41bfb532c7e/whisper/__init__.py#L126-L127).

2. **`TextToSpeechService`**: It also uses CUDA when available. You can see this in action here: [TTS CUDA Implementation](https://github.com/vndee/local-talking-llm/blob/32da24e4e152fe0154f8ef018789c87c65783361/tts.py#L14).

3. **Ollama LLM**: To enable CUDA for serving the Ollama model, follow the Linux setup guide here: [Ollama CUDA Setup](https://github.com/ollama/ollama/blob/main/docs/development.md#linux).
