### ISSUE TITLE
portaudio and punkt issue

### ISSUE THREAD

**Issue by adjei7** [vndee/local-talking-llm#3]
First of all, what you have done here is awesome. Thank you. This is by far one of the most simple ways to run ollama with whisper that I have seen. But I have run into a few issues.

1. When installing the dependencies via requirements.txt, pyaudio had issues installing, due to portaudio not present. Installing portaudio separately resolved the issue. Is it possible to include that in the requirements.txt file?

2. when running app.py, it seems like punkt is missing. Installing it seemed to sort it out.
3. Is there a way to have it install using a different default model instead of llama2. Something more lightweight like phi2? I'm trying to run this on a pi 5.

**Comment by exportio** [comment]
3.
ollama = Ollama(model="model_name")

Use ollama as llm property in ConversationChain

**Comment by vndee** [comment]
Hi @adjei7,
Thanks for your comment, here is some advices:
1. Can you try using `poetry` instead, this project was built and test under poetry env
2. This punk downloading is required for the first time of nltk running
3. You can use Ollama with model specific name as @exportio's comment

**Comment by vndee** [comment]
Hey @adjei7
You could try this: https://github.com/huggingface/parler-tts
